(() => {
  const canvas=document.getElementById('planCanvas'),ctx=canvas.getContext('2d'),stage=document.getElementById('stage');
  const S={tool:'select',items:[],selected:null,selection:[],clipboard:[],drawing:null,transform:null,pan:null,grid:true,snap:true,zoom:1,offset:{x:0,y:0},history:[],future:[],layers:{walls:true,openings:true,furniture:true,annotations:true}};
  const CLOUD_COLLECTION='merecad_planos';let currentUser=null,currentCloudId=null;
  const GRID=25, COLORS={wall:'#172521',room:'#d66b3d',door:'#a85e3c',window:'#3f7d83',dimension:'#64736e',text:'#172521'};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function resize(){const r=stage.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}
  function pos(e){const r=canvas.getBoundingClientRect();let x=(e.clientX-r.left-S.offset.x)/S.zoom,y=(e.clientY-r.top-S.offset.y)/S.zoom;if(S.snap){x=Math.round(x/GRID)*GRID;y=Math.round(y/GRID)*GRID}return{x,y}}
  function meters(n){return (Math.abs(n)/50).toFixed(2)+' m'}
  function snapshot(){S.history.push(JSON.stringify(S.items));if(S.history.length>60)S.history.shift();S.future=[]}
  function restore(arr){S.items=JSON.parse(arr);S.selected=null;S.selection=[];props();draw();save(false)}
  function selectedIndices(){return S.selection.length?S.selection:(S.selected===null?[]:[S.selected])}
  function selectIndex(index,add=false){if(index===null){if(!add){S.selected=null;S.selection=[]}return}const group=S.items[index].groupId,indices=group?S.items.map((o,i)=>o.groupId===group?i:null).filter(i=>i!==null):[index];if(add){indices.forEach(i=>{const at=S.selection.indexOf(i);if(at>=0)S.selection.splice(at,1);else S.selection.push(i)});S.selected=S.selection.length?S.selection[S.selection.length-1]:null}else{S.selection=[...indices];S.selected=index}}
  function lineDist(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return Math.hypot(p.x-a.x,p.y-a.y);let t=((p.x-a.x)*dx+(p.y-a.y)*dy)/l;t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}
  function hit(p){for(let i=S.items.length-1;i>=0;i--){const o=S.items[i];if(['room','symbol'].includes(o.type)&&p.x>=Math.min(o.x1,o.x2)-6&&p.x<=Math.max(o.x1,o.x2)+6&&p.y>=Math.min(o.y1,o.y2)-6&&p.y<=Math.max(o.y1,o.y2)+6)return i;if(o.type==='text'&&Math.hypot(p.x-o.x1,p.y-o.y1)<35)return i;if(lineDist(p,{x:o.x1,y:o.y1},{x:o.x2,y:o.y2})<10)return i}return null}
  function layerFor(t){return ['wall','room'].includes(t)?'walls':['door','window'].includes(t)?'openings':t==='symbol'?'furniture':'annotations'}
  function drawGrid(w,h){if(!S.grid)return;ctx.save();ctx.strokeStyle='#dfe3df';ctx.lineWidth=1;for(let x=(S.offset.x% (GRID*S.zoom));x<w;x+=GRID*S.zoom){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=(S.offset.y%(GRID*S.zoom));y<h;y+=GRID*S.zoom){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
  function drawPlanSymbol(c,o,x1=o.x1,y1=o.y1,x2=o.x2,y2=o.y2){const w=x2-x1,h=y2-y1,s=o.symbol;c.save();c.translate(x1,y1);c.scale(w/100,h/70);c.strokeStyle=o.color||'#31594e';c.fillStyle='#fff';c.lineWidth=2;c.lineJoin='round';c.lineCap='round';const rect=(x,y,a,b)=>c.strokeRect(x,y,a,b),ellipse=(x,y,rx,ry)=>{c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.stroke()},line=(ax,ay,bx,by)=>{c.beginPath();c.moveTo(ax,ay);c.lineTo(bx,by);c.stroke()};
    if(s==='WC'){rect(32,5,36,17);ellipse(50,40,22,24);ellipse(50,42,11,15);line(38,22,35,28);line(62,22,65,28)}
    else if(s==='LV'){ellipse(50,36,35,25);ellipse(50,38,25,16);ellipse(50,40,3,3);line(45,10,45,20);line(55,10,55,20);line(45,14,55,14)}
    else if(s==='RG'){rect(8,5,84,60);line(8,5,92,65);line(92,5,8,65);ellipse(50,35,5,5);c.setLineDash([3,3]);ellipse(50,35,30,22)}
    else if(s==='TN'){rect(5,5,90,60);c.beginPath();c.roundRect(13,12,74,46,20);c.stroke();ellipse(22,35,3,3)}
    else if(s==='FR'){rect(4,6,92,58);rect(10,12,37,40);rect(53,12,37,40);ellipse(28,32,3,3);ellipse(72,32,3,3);line(45,8,55,8);line(50,8,50,18)}
    else if(s==='ES'){rect(5,5,90,60);[[28,23],[72,23],[28,48],[72,48]].forEach(([x,y])=>{ellipse(x,y,12,10);ellipse(x,y,6,5)})}
    else if(s==='RF'){rect(15,3,70,64);line(50,3,50,67);line(43,14,43,29);line(57,14,57,29)}
    else if(s==='IS'){rect(3,10,94,50);rect(11,18,78,34);ellipse(34,35,8,8);ellipse(66,35,8,8)}
    else if(['C1','C2'].includes(s)){rect(4,3,92,64);rect(10,8,80,17);rect(13,10,34,12);rect(53,10,34,12);line(8,31,92,31);line(15,38,15,62);line(85,38,85,62)}
    else if(s==='BU'){rect(15,8,70,54);ellipse(50,35,4,4);line(20,20,80,20)}
    else if(s==='CL'){rect(5,8,90,54);line(35,8,35,62);line(65,8,65,62);line(10,55,30,15);line(40,55,60,15);line(70,55,90,15)}
    else if(s==='SO'||s==='SE3'){c.beginPath();c.roundRect(3,6,94,58,12);c.stroke();c.beginPath();c.roundRect(11,13,78,39,7);c.stroke();line(37,13,37,52);line(63,13,63,52);line(11,45,89,45);rect(5,15,7,34);rect(88,15,7,34)}
    else if(s==='SEC'){c.beginPath();c.roundRect(3,5,94,60,10);c.stroke();c.fillStyle='#fff';c.fillRect(46,28,53,39);c.strokeRect(46,28,51,37);line(13,27,88,27);line(31,8,31,27);line(63,8,63,27);line(57,35,88,35);line(57,35,57,60)}
    else if(s==='PO'){c.beginPath();c.roundRect(15,5,70,60,14);c.stroke();c.beginPath();c.roundRect(25,14,50,40,8);c.stroke();line(25,46,75,46);rect(17,19,9,30);rect(74,19,9,30)}
    else if(s==='MC'){c.beginPath();c.roundRect(8,12,84,46,14);c.stroke();c.beginPath();c.roundRect(16,20,68,30,10);c.stroke()}
    else if(s==='TD6'){c.beginPath();c.roundRect(17,9,66,52,12);c.stroke();[[8,20],[8,50],[92,20],[92,50],[35,3],[65,3]].forEach(([x,y])=>{c.beginPath();c.roundRect(x-7,y-6,14,12,3);c.stroke()})}
    else if(s==='BN'){c.beginPath();c.roundRect(5,18,90,34,8);c.stroke();line(15,52,15,65);line(85,52,85,65)}
    else if(s==='EO'){c.beginPath();c.roundRect(5,8,90,45,4);c.stroke();rect(12,15,37,30);line(57,16,87,16);line(57,24,87,24);c.beginPath();c.arc(50,64,15,Math.PI,Math.PI*2);c.stroke()}
    else if(s==='SOF'){c.beginPath();c.roundRect(27,12,46,35,10);c.stroke();ellipse(50,50,17,12);line(50,47,50,60);for(let a=0;a<5;a++){const q=a*Math.PI*2/5;line(50,60,50+Math.cos(q)*24,60+Math.sin(q)*8)}}
    else if(s==='LB'){rect(7,4,86,62);for(let x=20;x<90;x+=14)line(x,8,x,62);line(7,22,93,22);line(7,43,93,43)}
    else if(s==='JM'){c.beginPath();c.ellipse(50,35,35,25,0,0,Math.PI*2);c.stroke();for(let a=0;a<8;a++){const q=a*Math.PI*2/8,x=50+Math.cos(q)*45,y=35+Math.sin(q)*32;c.beginPath();c.roundRect(x-6,y-5,12,10,3);c.stroke()}}
    else if(s==='ME'){ellipse(50,35,28,27);ellipse(50,35,5,5);[[50,3],[50,67],[15,35],[85,35]].forEach(([x,y])=>rect(x-7,y-5,14,10))}
    else if(s==='SI'){c.beginPath();c.roundRect(22,12,56,48,8);c.stroke();line(27,20,73,20);line(27,55,27,66);line(73,55,73,66)}
    else if(s==='EC'){rect(4,8,92,46);line(12,54,12,66);line(88,54,88,66);rect(32,15,36,23);line(50,38,50,48)}
    else if(['LA','SE'].includes(s)){rect(12,3,76,64);ellipse(50,39,25,22);ellipse(50,39,17,15);ellipse(25,13,4,4);line(38,13,76,13)}
    else if(s==='BO'){ellipse(50,35,25,31);line(45,4,45,0);line(55,4,55,0);line(38,58,62,58)}
    else if(s==='AC'){rect(5,13,90,44);line(15,45,85,45);for(let i=0;i<4;i++)line(25+i*15,22,18+i*15,36)}
    else if(s==='AR'||s==='PL'){ellipse(50,35,31,28);ellipse(35,31,19,18);ellipse(63,29,21,20);line(50,42,50,67);line(50,52,39,62);line(50,53,61,62)}
    else if(s==='AU'){c.beginPath();c.roundRect(5,8,90,54,18);c.stroke();rect(25,15,50,40);line(25,27,75,27);line(25,48,75,48);ellipse(15,20,5,8);ellipse(85,20,5,8);ellipse(15,50,5,8);ellipse(85,50,5,8)}
    else if(s==='AS'){rect(8,8,84,52);rect(17,17,66,26);for(let i=0;i<5;i++)line(22+i*13,19,22+i*13,41);line(20,60,20,68);line(80,60,80,68)}
    else if(['CT','AP','LU','TB'].includes(s)){ellipse(50,35,22,22);line(28,35,72,35);line(50,13,50,57);c.font='700 18px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillStyle=o.color||'#31594e';c.fillText(s,50,35)}
    else{rect(8,8,84,54);c.font='700 18px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillStyle=o.color||'#31594e';c.fillText(s||'OBJ',50,35)}c.restore()}
  function drawItem(o,selected=false){if(!S.layers[layerFor(o.type)])return;ctx.save();ctx.strokeStyle=o.color||COLORS[o.type];ctx.fillStyle=o.color||COLORS[o.type];ctx.lineCap='round';const x1=o.x1,y1=o.y1,x2=o.x2,y2=o.y2;
    if(o.type==='wall'){ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='#f6f5f0';ctx.lineWidth=2;ctx.stroke()}
    else if(o.type==='room'){ctx.globalAlpha=.11;ctx.fillRect(x1,y1,x2-x1,y2-y1);ctx.globalAlpha=1;ctx.lineWidth=7;ctx.strokeRect(x1,y1,x2-x1,y2-y1);if(o.label){ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(o.label,(x1+x2)/2,(y1+y2)/2)}}
    else if(o.type==='door'){ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const r=Math.hypot(x2-x1,y2-y1);ctx.lineWidth=1;ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(x1,y1,r,Math.atan2(y2-y1,x2-x1)-Math.PI/2,Math.atan2(y2-y1,x2-x1));ctx.stroke()}
    else if(o.type==='window'){ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke()}
    else if(o.type==='dimension'){ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.font='11px sans-serif';ctx.textAlign='center';ctx.fillStyle='#53615b';ctx.fillText(meters(Math.hypot(x2-x1,y2-y1)),(x1+x2)/2,(y1+y2)/2-7)}
    else if(o.type==='text'){ctx.font='14px sans-serif';ctx.fillText(o.label||'Texto',x1,y1)}
    else if(o.type==='symbol'){drawPlanSymbol(ctx,o,x1,y1,x2,y2)}
    if(selected){ctx.strokeStyle='#e67443';ctx.fillStyle='#e67443';ctx.lineWidth=1;ctx.setLineDash([4,3]);const minx=Math.min(x1,x2)-9,miny=Math.min(y1,y2)-9;ctx.strokeRect(minx,miny,Math.abs(x2-x1)+18||45,Math.abs(y2-y1)+18||22);for(const p of [{x:x1,y:y1},{x:x2,y:y2}]){ctx.setLineDash([]);ctx.beginPath();ctx.arc(p.x,p.y,4,0,7);ctx.fill()}}
    ctx.restore()}
  function draw(){const r=stage.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#f2f3f0';ctx.fillRect(0,0,r.width,r.height);drawGrid(r.width,r.height);ctx.save();ctx.translate(S.offset.x,S.offset.y);ctx.scale(S.zoom,S.zoom);const chosen=selectedIndices();S.items.forEach((o,i)=>drawItem(o,chosen.includes(i)));if(S.drawing)drawItem(S.drawing,false);ctx.restore();$('#emptyHint').style.display=S.items.length?'none':'flex';$('#zoomLabel').textContent=Math.round(S.zoom*100)+'%'}
  function setTool(t){S.tool=t;$$('.tool,.ribbon-tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));canvas.style.cursor=t==='select'?'default':'crosshair'}
  canvas.addEventListener('pointerdown',e=>{if(e.button===1){e.preventDefault();S.pan={x:e.clientX,y:e.clientY,ox:S.offset.x,oy:S.offset.y};canvas.style.cursor='grabbing';canvas.setPointerCapture(e.pointerId);return}const p=pos(e);stage.focus();if(S.tool==='select'){const found=hit(p);selectIndex(found,e.shiftKey);if(found!==null&&!e.shiftKey){const o=S.items[found],near1=Math.hypot(p.x-o.x1,p.y-o.y1)<14/S.zoom,near2=Math.hypot(p.x-o.x2,p.y-o.y2)<14/S.zoom;snapshot();const originals={};selectedIndices().forEach(i=>originals[i]={x1:S.items[i].x1,y1:S.items[i].y1,x2:S.items[i].x2,y2:S.items[i].y2});S.transform={mode:selectedIndices().length===1&&near1?'resize1':selectedIndices().length===1&&near2?'resize2':'move',start:p,originals};canvas.setPointerCapture(e.pointerId)}props();draw();return}snapshot();if(S.tool==='text'){const label=prompt('Texto de la anotación:','Habitación');if(label)S.items.push({type:'text',x1:p.x,y1:p.y,x2:p.x,y2:p.y,label,color:COLORS.text});S.drawing=null;save();draw();return}S.drawing={type:S.tool,x1:p.x,y1:p.y,x2:p.x,y2:p.y,color:COLORS[S.tool],label:S.tool==='room'?'Habitación':''};canvas.setPointerCapture(e.pointerId)});
  canvas.addEventListener('pointermove',e=>{if(S.pan){S.offset.x=S.pan.ox+e.clientX-S.pan.x;S.offset.y=S.pan.oy+e.clientY-S.pan.y;draw();return}const p=pos(e);$('#cursorCoords').textContent=meters(p.x)+', '+meters(p.y);if(S.transform&&S.selected!==null){const t=S.transform;if(t.mode==='move'){const dx=p.x-t.start.x,dy=p.y-t.start.y;selectedIndices().forEach(i=>{const o=S.items[i],a=t.originals[i];o.x1=a.x1+dx;o.y1=a.y1+dy;o.x2=a.x2+dx;o.y2=a.y2+dy})}else{const o=S.items[S.selected];if(t.mode==='resize1'){o.x1=p.x;o.y1=p.y}else{o.x2=p.x;o.y2=p.y}}props();draw();return}if(S.drawing){S.drawing.x2=p.x;S.drawing.y2=p.y;draw()}});
  canvas.addEventListener('pointerup',()=>{if(S.pan){S.pan=null;setTool(S.tool);return}if(S.transform){S.transform=null;save(false);props();draw();return}if(!S.drawing)return;const o=S.drawing;S.drawing=null;if(Math.hypot(o.x2-o.x1,o.y2-o.y1)>8){S.items.push(o);S.selected=S.items.length-1;S.selection=[S.selected];props();save()}draw()});
  function props(){const o=S.items[S.selected],count=selectedIndices().length;$('#noSelection').hidden=!!o;$('#selectionProps').hidden=!o;if(!o)return;$('#propType').value=count>1?count+' elementos seleccionados':({wall:'Muro',room:'Habitación',door:'Puerta',window:'Ventana',dimension:'Cota',text:'Texto',symbol:'Figura'})[o.type];$('#propLabel').value=count>1?'':o.label||'';$('#propLabel').disabled=count>1;$('#propColor').value=o.color||COLORS[o.type]||'#31594e';$('#propLength').value=count>1?'Selección múltiple':o.type==='room'?meters(Math.abs(o.x2-o.x1))+' × '+meters(Math.abs(o.y2-o.y1)):o.type==='symbol'?meters(Math.abs(o.x2-o.x1))+' × '+meters(Math.abs(o.y2-o.y1)):meters(Math.hypot(o.x2-o.x1,o.y2-o.y1));$('#propX').value=(Math.min(o.x1,o.x2)/50).toFixed(2);$('#propY').value=(Math.min(o.y1,o.y2)/50).toFixed(2);$('#propWidth').value=(Math.abs(o.x2-o.x1)/50).toFixed(2);$('#propHeight').value=(Math.abs(o.y2-o.y1)/50).toFixed(2)}
  function save(show=false){localStorage.setItem('merecad-plan',JSON.stringify({items:S.items,name:$('#projectName').value}));if(currentCloudId)$('#saveState').textContent='Cambios sin guardar';else $('#saveState').textContent='Borrador local';if(show)toast('Borrador guardado en este dispositivo')}
  function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
  function undo(){if(!S.history.length)return;S.future.push(JSON.stringify(S.items));restore(S.history.pop())}function redo(){if(!S.future.length)return;S.history.push(JSON.stringify(S.items));restore(S.future.pop())}
  $$('.tool,.ribbon-tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$$('.ribbon-action').forEach(b=>b.onclick=()=>{const a=b.dataset.action,actions={duplicate:'#duplicateBtn',group:'#groupBtn',ungroup:'#ungroupBtn',rotate:'#rotateBtn',delete:'#deleteBtn',alignLeft:'#alignLeft',alignTop:'#alignTop',alignHCenter:'#alignHCenter',alignVCenter:'#alignVCenter',front:'#bringFront',back:'#sendBack'};if(a==='move')setTool('select');else if(a==='copy')copySelection();else if(a==='paste')pasteSelection();else $(actions[a]).click();b.closest('details')?.removeAttribute('open')});$$('.command-menu').forEach(menu=>menu.addEventListener('toggle',()=>{if(menu.open)$$('.command-menu').filter(other=>other!==menu).forEach(other=>other.removeAttribute('open'))}));$('#gridBtn').onclick=e=>{S.grid=!S.grid;e.currentTarget.classList.toggle('active',S.grid);draw()};$('#snapBtn').onclick=e=>{S.snap=!S.snap;e.currentTarget.classList.toggle('active',S.snap)};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#saveBtn').onclick=saveCloudPlan;
  $('#deleteBtn').onclick=()=>{const ids=selectedIndices().sort((a,b)=>b-a);if(!ids.length)return;snapshot();ids.forEach(i=>S.items.splice(i,1));S.selected=null;S.selection=[];props();save();draw()};
  $('#propLabel').oninput=e=>{S.items[S.selected].label=e.target.value;save(false);draw()};$('#propColor').oninput=e=>{S.items[S.selected].color=e.target.value;save(false);draw()};
  function mutateSelected(fn){if(S.selected===null)return;snapshot();fn(S.items[S.selected]);save(false);props();draw()}
  function mutateSelection(fn){const ids=selectedIndices();if(!ids.length)return;snapshot();ids.forEach((i,n)=>fn(S.items[i],i,n));save(false);props();draw()}
  function moveSelected(dx,dy){mutateSelection(o=>{o.x1+=dx;o.x2+=dx;o.y1+=dy;o.y2+=dy})}
  function duplicate(){const ids=selectedIndices();if(!ids.length)return;snapshot();const start=S.items.length,newIds=[];ids.forEach((i,n)=>{const o=JSON.parse(JSON.stringify(S.items[i]));o.x1+=GRID;o.x2+=GRID;o.y1+=GRID;o.y2+=GRID;S.items.push(o);newIds.push(start+n)});S.selection=newIds;S.selected=newIds[newIds.length-1];save(false);props();draw();toast(ids.length+' elemento(s) duplicado(s)')}
  function copySelection(){const ids=selectedIndices();if(!ids.length)return toast('Primero selecciona uno o más elementos');S.clipboard=ids.map(i=>JSON.parse(JSON.stringify(S.items[i])));toast(ids.length+' elemento(s) copiado(s)')}
  function pasteSelection(){if(!S.clipboard.length)return toast('No hay elementos copiados');snapshot();const start=S.items.length;S.clipboard.forEach(o=>{const copy=JSON.parse(JSON.stringify(o));copy.x1+=GRID;copy.x2+=GRID;copy.y1+=GRID;copy.y2+=GRID;S.items.push(copy)});S.selection=S.clipboard.map((_,i)=>start+i);S.selected=S.selection.at(-1);save(false);props();draw();toast(S.clipboard.length+' elemento(s) pegado(s)')}
  function numericEdit(){const o=S.items[S.selected];if(!o)return;const minX=Math.min(o.x1,o.x2),minY=Math.min(o.y1,o.y2),sx=o.x2>=o.x1?1:-1,sy=o.y2>=o.y1?1:-1;const x=parseFloat($('#propX').value)*50,y=parseFloat($('#propY').value)*50,w=Math.max(0,parseFloat($('#propWidth').value)*50),h=Math.max(0,parseFloat($('#propHeight').value)*50);snapshot();const dx=x-minX,dy=y-minY;o.x1+=dx;o.x2+=dx;o.y1+=dy;o.y2+=dy;if(Number.isFinite(w))o.x2=o.x1+sx*w;if(Number.isFinite(h))o.y2=o.y1+sy*h;save(false);props();draw()}
  ['#propX','#propY','#propWidth','#propHeight'].forEach(id=>$(id).onchange=numericEdit);
  $('#duplicateBtn').onclick=duplicate;
  $('#bringFront').onclick=()=>{const ids=selectedIndices().sort((a,b)=>a-b);if(!ids.length)return;snapshot();const chosen=ids.map(i=>S.items[i]);S.items=S.items.filter((_,i)=>!ids.includes(i)).concat(chosen);S.selection=chosen.map((_,n)=>S.items.length-chosen.length+n);S.selected=S.selection.at(-1);save(false);draw()};
  $('#sendBack').onclick=()=>{const ids=selectedIndices().sort((a,b)=>a-b);if(!ids.length)return;snapshot();const chosen=ids.map(i=>S.items[i]);S.items=chosen.concat(S.items.filter((_,i)=>!ids.includes(i)));S.selection=chosen.map((_,i)=>i);S.selected=S.selection.at(-1);save(false);draw()};
  function selectionBounds(){const a=selectedIndices().map(i=>S.items[i]);return{left:Math.min(...a.map(o=>Math.min(o.x1,o.x2))),right:Math.max(...a.map(o=>Math.max(o.x1,o.x2))),top:Math.min(...a.map(o=>Math.min(o.y1,o.y2))),bottom:Math.max(...a.map(o=>Math.max(o.y1,o.y2)))}}
  $('#alignLeft').onclick=()=>{const b=selectionBounds();mutateSelection(o=>{const d=b.left-Math.min(o.x1,o.x2);o.x1+=d;o.x2+=d})};
  $('#alignTop').onclick=()=>{const b=selectionBounds();mutateSelection(o=>{const d=b.top-Math.min(o.y1,o.y2);o.y1+=d;o.y2+=d})};
  $('#alignHCenter').onclick=()=>{const b=selectionBounds(),c=(b.left+b.right)/2;mutateSelection(o=>{const d=c-(o.x1+o.x2)/2;o.x1+=d;o.x2+=d})};
  $('#alignVCenter').onclick=()=>{const b=selectionBounds(),c=(b.top+b.bottom)/2;mutateSelection(o=>{const d=c-(o.y1+o.y2)/2;o.y1+=d;o.y2+=d})};
  $('#groupBtn').onclick=()=>{const ids=selectedIndices();if(ids.length<2)return toast('Selecciona dos o más elementos');const id='g'+Date.now();mutateSelection(o=>o.groupId=id);toast('Elementos agrupados')};
  $('#ungroupBtn').onclick=()=>{mutateSelection(o=>delete o.groupId);toast('Grupo separado')};
  $('#rotateBtn').onclick=()=>{const b=selectionBounds(),cx=(b.left+b.right)/2,cy=(b.top+b.bottom)/2;mutateSelection(o=>{const ax=cx-(o.y1-cy),ay=cy+(o.x1-cx),bx=cx-(o.y2-cy),by=cy+(o.x2-cx);o.x1=ax;o.y1=ay;o.x2=bx;o.y2=by});toast('Selección girada 90°')};
  function addSymbolAt(symbol,label,x,y){const sizes={WC:[38,55],LV:[55,40],RG:[50,50],TN:[90,42],FR:[75,40],ES:[60,60],RF:[45,80],IS:[100,50],C1:[50,95],C2:[80,95],BU:[35,35],CL:[100,35],SO:[100,45],SE3:[110,48],SEC:[110,85],PO:[55,55],MC:[70,40],TD6:[100,75],BN:[75,30],ME:[70,70],SI:[35,35],EC:[80,45],EO:[90,60],SOF:[45,45],LB:[95,30],JM:[110,80],LA:[45,50],SE:[45,50],BO:[35,60],AC:[80,30],AU:[90,45],AR:[65,65],PL:[35,35],AS:[65,45],CT:[25,25],AP:[25,25],LU:[30,30],TB:[40,50]},size=sizes[symbol]||[70,50],w=size[0],h=size[1];snapshot();S.items.push({type:'symbol',symbol,label,x1:x-w/2,y1:y-h/2,x2:x+w/2,y2:y+h/2,color:'#31594e'});S.selected=S.items.length-1;S.selection=[S.selected];setTool('select');save(false);props();draw();toast(label+' añadido')}
  $$('.shape').forEach(button=>{button.addEventListener('click',()=>{const x=(stage.clientWidth/2-S.offset.x)/S.zoom,y=(stage.clientHeight/2-S.offset.y)/S.zoom;addSymbolAt(button.dataset.symbol,button.dataset.label,x,y)});button.addEventListener('dragstart',e=>{e.dataTransfer.setData('application/merecad-shape',JSON.stringify({symbol:button.dataset.symbol,label:button.dataset.label}));e.dataTransfer.effectAllowed='copy'})});
  $$('.shape').forEach(button=>{const preview=document.createElement('canvas');preview.className='shape-preview';preview.width=128;preview.height=80;button.insertBefore(preview,button.firstChild);const pc=preview.getContext('2d');pc.scale(2,2);drawPlanSymbol(pc,{symbol:button.dataset.symbol,color:'#31594e'},3,2,61,38)});
  canvas.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/merecad-shape')){e.preventDefault();e.dataTransfer.dropEffect='copy'}});
  canvas.addEventListener('drop',e=>{const raw=e.dataTransfer.getData('application/merecad-shape');if(!raw)return;e.preventDefault();const shape=JSON.parse(raw),p=pos(e);addSymbolAt(shape.symbol,shape.label,p.x,p.y)});
  $$('.layers input').forEach(x=>x.onchange=()=>{S.layers[x.dataset.layer]=x.checked;draw()});
  function zoomAt(nextZoom,screenX,screenY){nextZoom=Math.max(.2,Math.min(5,nextZoom));const worldX=(screenX-S.offset.x)/S.zoom,worldY=(screenY-S.offset.y)/S.zoom;S.zoom=nextZoom;S.offset.x=screenX-worldX*S.zoom;S.offset.y=screenY-worldY*S.zoom;draw()}
  canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,factor=e.deltaY<0?1.12:1/1.12;zoomAt(S.zoom*factor,x,y)},{passive:false});
  $('#zoomIn').onclick=()=>zoomAt(S.zoom*1.15,stage.clientWidth/2,stage.clientHeight/2);$('#zoomOut').onclick=()=>zoomAt(S.zoom/1.15,stage.clientWidth/2,stage.clientHeight/2);$('#zoomFit').onclick=()=>{S.zoom=1;S.offset={x:0,y:0};draw()};
  $('#exportBtn').onclick=()=>{const old=S.selected;S.selected=null;draw();const a=document.createElement('a');a.download=($('#projectName').value||'plano').replace(/\s+/g,'-').toLowerCase()+'.png';a.href=canvas.toDataURL('image/png');a.click();S.selected=old;draw();toast('Plano exportado como PNG')};
  addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;const key=e.key.toLowerCase(),mod=e.ctrlKey||e.metaKey,map={v:'select',w:'wall',r:'room',d:'door',n:'window',m:'dimension',t:'text'};if(map[key]&&!mod)setTool(map[key]);if(mod&&key==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(mod&&key==='y')redo();if(mod&&key==='d'){e.preventDefault();duplicate()}if(mod&&key==='c'){e.preventDefault();S.clipboard=selectedIndices().map(i=>JSON.parse(JSON.stringify(S.items[i])));toast('Selección copiada')}if(mod&&key==='v'&&S.clipboard.length){e.preventDefault();snapshot();const start=S.items.length;S.clipboard.forEach(o=>{const copy=JSON.parse(JSON.stringify(o));copy.x1+=GRID;copy.x2+=GRID;copy.y1+=GRID;copy.y2+=GRID;S.items.push(copy)});S.selection=S.clipboard.map((_,i)=>start+i);S.selected=S.selection.at(-1);save(false);props();draw();toast('Selección pegada')}if(mod&&key==='g'){e.preventDefault();$('#groupBtn').click()}if((e.key==='Delete'||e.key==='Backspace')&&S.selected!==null)$('#deleteBtn').click();const arrows={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(arrows[e.key]&&S.selected!==null){e.preventDefault();const step=e.shiftKey?GRID:1;moveSelected(arrows[e.key][0]*step,arrows[e.key][1]*step)}});
  function waitFirebase(){if(window.merecadFirebase)return Promise.resolve(window.merecadFirebase);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Firebase no disponible')),8000);addEventListener('merecad:firebase-ready',()=>{clearTimeout(timer);resolve(window.merecadFirebase)},{once:true});addEventListener('merecad:firebase-error',()=>{clearTimeout(timer);reject(new Error('No se pudo iniciar Firebase'))},{once:true})})}
  function authMessage(error){const messages={'auth/invalid-credential':'Correo o contraseña incorrectos.','auth/email-already-in-use':'Ese correo ya está registrado.','auth/weak-password':'La contraseña debe tener al menos 6 caracteres.','auth/network-request-failed':'No se pudo conectar con Firebase.','permission-denied':'Las reglas de Firestore bloquearon esta operación.'};return messages[error?.code]||error?.message||'No se pudo completar la operación.'}
  function setAuthMode(register=false){$('#loginForm').hidden=register;$('#registerForm').hidden=!register}
  async function saveCloudPlan(){if(!currentUser)return toast('Inicia sesión para guardar');try{const f=await waitFirebase(),payload={name:$('#projectName').value.trim()||'Dibujo 1',items:S.items,view:{zoom:S.zoom,offset:S.offset},ownerId:currentUser.uid,ownerEmail:currentUser.email||'',appVersion:'2.2',updatedAt:f.serverTimestamp()};if(currentCloudId)await f.setDoc(f.doc(f.db,CLOUD_COLLECTION,currentCloudId),payload,{merge:true});else{const ref=await f.addDoc(f.collection(f.db,CLOUD_COLLECTION),{...payload,createdAt:f.serverTimestamp()});currentCloudId=ref.id}localStorage.setItem('merecad-plan',JSON.stringify({items:S.items,name:payload.name}));$('#saveState').textContent='Guardado en la nube';toast('Plano guardado en Firebase')}catch(error){console.error('Guardar plano',error);toast(authMessage(error))}}
  async function loadCloudPlans(){const list=$('#cloudList');list.innerHTML='<p class="cloud-empty">Cargando…</p>';$('#cloudDialog').showModal();try{const f=await waitFirebase(),snap=await f.getDocs(f.query(f.collection(f.db,CLOUD_COLLECTION),f.where('ownerId','==',currentUser.uid))),records=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));list.innerHTML='';if(!records.length){list.innerHTML='<p class="cloud-empty">Aún no tienes dibujos guardados.</p>';return}records.forEach(record=>{const row=document.createElement('div');row.className='cloud-record';const info=document.createElement('div'),actions=document.createElement('div'),open=document.createElement('button'),del=document.createElement('button');info.innerHTML='<b></b><small></small>';info.querySelector('b').textContent=record.name||'Dibujo sin nombre';info.querySelector('small').textContent='Actualizado '+(record.updatedAt?.toDate?.().toLocaleString('es-MX')||'recientemente');actions.className='record-actions';open.textContent='Abrir';del.textContent='Eliminar';del.className='delete-cloud';open.onclick=()=>{S.items=Array.isArray(record.items)?record.items:[];S.zoom=record.view?.zoom||1;S.offset=record.view?.offset||{x:0,y:0};S.selected=null;S.selection=[];S.history=[];S.future=[];currentCloudId=record.id;$('#projectName').value=record.name||'Dibujo 1';save(false);$('#saveState').textContent='Guardado en la nube';$('#cloudDialog').close();props();draw();toast('Plano abierto')};del.onclick=async()=>{if(!confirm('¿Eliminar este dibujo de la nube?'))return;await f.deleteDoc(f.doc(f.db,CLOUD_COLLECTION,record.id));if(currentCloudId===record.id)currentCloudId=null;row.remove();toast('Dibujo eliminado')};actions.append(open,del);row.append(info,actions);list.append(row)})}catch(error){list.innerHTML='<p class="cloud-empty"></p>';list.querySelector('p').textContent=authMessage(error)}}
  $('#openBtn').onclick=loadCloudPlans;$('#closeCloudDialog').onclick=()=>$('#cloudDialog').close();$('#newBtn').onclick=()=>{if(S.items.length&&!confirm('¿Crear un dibujo nuevo? El borrador actual permanecerá en este dispositivo.'))return;S.items=[];S.selection=[];S.selected=null;S.history=[];S.future=[];S.zoom=1;S.offset={x:0,y:0};currentCloudId=null;$('#projectName').value='Dibujo 1';save(false);props();draw();toast('Nuevo dibujo')};
  $('#showRegisterButton').onclick=()=>setAuthMode(true);$('#showLoginButton').onclick=()=>setAuthMode(false);$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMessage').textContent='Entrando…';try{const f=await waitFirebase();await f.signInWithEmailAndPassword(f.auth,$('#loginEmailInput').value.trim().toLowerCase(),$('#loginPasswordInput').value);$('#loginMessage').textContent=''}catch(error){$('#loginMessage').textContent=authMessage(error)}};$('#registerForm').onsubmit=async e=>{e.preventDefault();$('#registerMessage').textContent='Creando cuenta…';try{const f=await waitFirebase(),credential=await f.createUserWithEmailAndPassword(f.auth,$('#registerEmailInput').value.trim().toLowerCase(),$('#registerPasswordInput').value),name=$('#registerNameInput').value.trim();await f.updateProfile(credential.user,{displayName:name});await f.setDoc(f.doc(f.db,'users',credential.user.uid),{name,email:credential.user.email,role:'usuario',updatedAt:f.serverTimestamp()},{merge:true});$('#registerMessage').textContent=''}catch(error){$('#registerMessage').textContent=authMessage(error)}};$('#signOutButton').onclick=async()=>{const f=await waitFirebase();await f.signOut(f.auth)};
  waitFirebase().then(f=>f.onAuthStateChanged(f.auth,user=>{currentUser=user||null;currentCloudId=null;if(user){$('#authView').hidden=true;document.body.classList.remove('auth-pending');$('#currentUserLabel').textContent=user.displayName||user.email;resize()}else{$('#authView').hidden=false;document.body.classList.add('auth-pending');$('#currentUserLabel').textContent='';setAuthMode(false)}})).catch(error=>{$('#loginMessage').textContent=authMessage(error);$('#authView').hidden=false});
  const stored=localStorage.getItem('merecad-plan')||localStorage.getItem('trazo-plan');if(stored){try{const d=JSON.parse(stored);S.items=d.items||[];$('#projectName').value=!d.name||d.name==='Casa Roble'?'Dibujo 1':d.name}catch{}}$('#projectName').oninput=()=>{$('#saveState').textContent='Cambios sin guardar'};
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});addEventListener('resize',resize);resize();
})();
